### ISSUE TITLE
Better log when the container failed to be ready

### ISSUE THREAD

**Issue by khalilou88** [testcontainers/testcontainers-node#145]
Hello,

Thank you for this project.
I try to start a container but for some reason the container failed to be ready.
With debug, I can't know the reason : 

  testcontainers DEBUG Creating new DockerClient +0ms
  testcontainers INFO Using default Docker host: localhost, socket path: //./pipe/docker_engine +4ms
  testcontainers DEBUG Creating new Reaper for session: 9c4db888f30a0e7cb669b5d6102949b4 +41ms
  testcontainers INFO Creating container for image: testcontainers/ryuk:0.3.0 +13ms
  testcontainers INFO Starting container with ID: f57a4a0a104b4cbf0568d2e81a30aa1c30c4da16e4a5a7f3f4ae99dc8ecda038 +1s
  testcontainers DEBUG Waiting for container to be ready: f57a4a0a104b4cbf0568d2e81a30aa1c30c4da16e4a5a7f3f4ae99dc8ecda038 +289ms
  testcontainers DEBUG Waiting for log message "Started!" +2ms
  **testcontainers ERROR Container failed to be ready +37ms**
  testcontainers INFO Container has already been stopped: f57a4a0a104b4cbf0568d2e81a30aa1c30c4da16e4a5a7f3f4ae99dc8ecda038 +136ms
  testcontainers ERROR Failed to stop container after it failed to be ready +12ms

Maybe we can log the error here so we will know more about the error ?

    } catch (err) {
      log.error("Container failed to be ready");

Thanks

**Comment by cristianrgreco** [comment]
Hi @khalilou88, thanks!

You can set `DEBUG=testcontainers*` to see the container output, that would show any error if there is one.

**Comment by cristianrgreco** [comment]
@khalilou88 was my message able to help / can I close this issue?

**Comment by khalilou88** [comment]
thanks for your reply.
yes you can close this issue.
the problem is with my docker

**Comment by totalamd** [comment]
In my case containers starts ok from CLI but
```
  testcontainers DEBUG Waiting for log message "Started!" +2ms
  testcontainers ERROR Container failed to be ready +64msfor different containers 
```
for different containers. Neither ain't error for `catch(e)`, just `undefined`.

**Comment by cristianrgreco** [comment]
@totalamd Could you set `DEBUG=testcontainers*` and run it again? Also share what version of testcontainers-node you're using and ideally a repro of the issue

**Comment by totalamd** [comment]
Hi, @cristianrgreco,
I have docker 2.4.0.0, engine 19.03.13, windows 10.
I'm trying this minimal code and in node repl, with the same result:
```
let TC = require('testcontainers');
let c = await new TC.GenericContainer('postgres').start();
```
I found any testcontiners v4.x.x gives an error on my machine (not only postgres, but anything I've tried):
```
  testcontainers DEBUG Creating new DockerClient +0ms
  testcontainers INFO Using default Docker host: localhost, socket path: //./pipe/docker_engine +3ms
  testcontainers DEBUG Creating new Reaper for session: faec0c9a04913f5ee29d45867c80c62f +32ms
  testcontainers INFO Creating container for image: testcontainers/ryuk:0.3.0 +16ms
  testcontainers INFO Starting container with ID: 2cd75555783dd614ad096578b972dfc5a408b43aa36837031867297ef9aa0ecb +1s
  testcontainers DEBUG Waiting for container to be ready: 2cd75555783dd614ad096578b972dfc5a408b43aa36837031867297ef9aa0ecb +368ms
  testcontainers DEBUG Waiting for log message "Started!" +28ms
  testcontainers ERROR Container failed to be ready +58ms
  testcontainers INFO Container has already been stopped: 2cd75555783dd614ad096578b972dfc5a408b43aa36837031867297ef9aa0ecb +142ms
  testcontainers ERROR Failed to stop container after it failed to be ready +14ms
```
also the error in catch() is always `undefined`,
while v3.5.0 works fine:
```
  testcontainers INFO Using default Docker host: localhost, socket path: //./pipe/docker_engine +0ms
  testcontainers INFO Creating container for image: postgres:11.4 +23ms
  testcontainers INFO Starting container with ID: 5a1d3d815c6bbb6fe0759bb465a0b5e937b71fbacd153444192504cc973bcd21 +2s
  testcontainers DEBUG Waiting for container to be ready: 5a1d3d815c6bbb6fe0759bb465a0b5e937b71fbacd153444192504cc973bcd21 +323ms
  testcontainers INFO Container is ready +2ms
```

**Comment by cristianrgreco** [comment]
Thanks that's useful information. The major difference between 3.x.x and 4.x.x is that there is a "reaper" container called ryuk which starts by default before any container. It seems from your logs that this container is failing to start. Are you able to debug from the CLI why the ryuk container is failing to start? It's hard for me to get a hold of a Windows machine so that'd be helpful

**Comment by totalamd** [comment]
Could you give me a link/hint how to debug it properly inside testcontainers? I'm quite new to the docker. The image starts ok via docker cli.

**Comment by totalamd** [comment]
@cristianrgreco Could you give me a link/hint how to debug it properly inside testcontainers? I'm quite new to the docker. The image starts ok via docker cli.

**Comment by cristianrgreco** [comment]
@totalamd Do you see the ryuk container if you run `docker ps -a`? If you do could you share the logs (`docker logs <id>`)? This is the line that's failing https://github.com/testcontainers/testcontainers-node/blob/master/src/reaper.ts#L34, you could checkout the repo and run one of the `GenericContainer` tests to debug what's happening

**Comment by pjroth** [comment]
We had a similar symptom today:
```
estcontainers DEBUG Creating new DockerClient +0ms
  testcontainers INFO Using default Docker host: localhost, socket path: //./pipe/docker_engine +1ms
Promise { <pending> }
  testcontainers DEBUG Creating new Reaper for session: d83c9172afa3e2967951b5abe3d8b494 +57ms
  testcontainers INFO Creating container for image: testcontainers/ryuk:0.3.0 +36ms
  testcontainers INFO Starting container with ID: 9202a3dfbe6b28e53955b17de339f37bf2722fd2421ab81465bff660a2f6fb0b +1s
  testcontainers DEBUG Waiting for container to be ready: 9202a3dfbe6b28e53955b17de339f37bf2722fd2421ab81465bff660a2f6fb0b +318ms
  testcontainers DEBUG Waiting for log message "Started!" +1ms
  testcontainers ERROR Container failed to be ready +53ms
  testcontainers ERROR Failed to stop container after it failed to be ready +551ms
```

This was from a developer on windows with docker desktop.  We had not seen this issue on linux (using the standard /var/run/docker.sock).  The problem we determined was that ryuk fails to startup successfully on windows when using the standard Docker Desktop socket.  However, the lack of log output from the ryuk container even when using `DEBUG="testcontainers*"` made this very hard to debug. We ended up finding the code that launches ryuk in this repository and crafted a `docker run` command that matched it best we could.  The output from ryuk then clearly stated the problem was with the connection to the docker daemon.  

We fixed this on by setting on the windows host, `DOCKER_HOST="tcp://localhost:2375"` (and checked the box in Docker Desktop settings to enable this which may be disabled by default).  After this ryuk started up successfully.

What I would prefer to see is when using `DEBUG="testcontainers*"` I would like to see ALL the output from ALL containers including ryuk so that any issues can be more easily diagnosed.  Additionally having a specific check for windows docker desktop socket would be best so that a specific error can be given in this situation with helpful instructions for Docker Desktop users.

Thanks for all the hard work on this repository!

**Comment by cristianrgreco** [comment]
@pjroth Thanks for sharing! I managed to get my hands on a Windows machine and worked my way through a bunch of issues, it's now all working, even able to run the build on Windows!

Check out the attached PR, it should resolve this issue as well as others, and importantly as you said it now outputs the logs of ALL containers (including ryuk), which should mean people never have such a hard time debugging this again 🙂

**Comment by cristianrgreco** [comment]
Released in v4.5.0

**Comment by khalilou88** [comment]
thanks working for me now 👍

**Comment by pjroth** [comment]
Thanks so much for the quick turnaround on this fix!
