### ISSUE TITLE
[Question] EventStoreDB pre-prepared module

### ISSUE THREAD

**Issue by oskardudycz** [testcontainers/testcontainers-node#217]
@cristianrgreco, would you be willing to take a PR with [EventStoreDB](https://developers.eventstore.com/) module? I'd be happy to send it if you're open to such a contribution.

If yes, then I would be grateful if you have some suggestions or guidelines besides having a look at other pre-configured modules :)

**Comment by oskardudycz** [comment]
My draft (but working) EventStoreDB module looks as follows:

https://github.com/oskardudycz/EventSourcing.NodeJS/blob/snapshots/samples/snapshots/src/testing/eventStoreDB/eventStoreDBContainer.ts

I needed to use renamed method `startContainer` instead of `start` as my class `StartedEventStoreDBContainer` cannot implement `StartedTestContainer` without copy/pasting classes definitions (as they seems to not be exported).

Thoughts?

**Comment by cristianrgreco** [comment]
Hi @oskardudycz, the existing modules are part of the `testcontainers-node` project, not separate repositories, which is why the other modules are able to import the types they need. See here an example of a module:

https://github.com/testcontainers/testcontainers-node/blob/f58fe65acbbf1959c61416ad23a8727a7c8ca4e0/src/modules/elasticsearch/elasticsearch-container.ts#L9-L30
