### ISSUE TITLE
Feature: add environment variable for scaling "withStartupTimeout"

### ISSUE THREAD

**Issue by mderrien29** [testcontainers/testcontainers-node#323]
**Issue :** Test will fail if the container has not started in allocated time. Depending on environment the tests will "randomly" fail.

**Why :** Some environments might have limited performances (low spec machines, slow CI runner, etc) or limited connectivity (inital pull of images, new image, etc). Some might even have sufficient performances and only encounter issues when multitasking with other applications using too much ressources (eg slack, teams, vscode, web browsers...)

**Current solution :** Current way to handle this is to include a [.withStartupTimeout(ms)](https://www.testcontainers.org/features/startup_and_waits/) option on container startup to replace the default 60s of waiting time. However this value could have to change over time, and it's not optimal to include a big value because your CI runner is slow. It seems like it would be easier if the library could handle it OOB.

**Proposition :** Include an environment variable to replace the current default (60s) timeout

eg. `TESTCONTAINERS_DEFAULT_STARTUP_TIMEOUT` = 120

It could also be in the form of a scaling value 

eg. `TESTCONTAINERS_STARTUP_TIMEOUT_SCALING` = 2

Would a PR on this be accepted ?

**Comment by cristianrgreco** [comment]
hi @mderrien29, thanks for raising! it sounds like a good idea to me, and `TESTCONTAINERS_DEFAULT_STARTUP_TIMEOUT` sounds good 👍

**Comment by cristianrgreco** [comment]
hey @mderrien29, so I was speaking to some of the tc-java folks and they made a good point, what is stopping you from doing something like: `withStartupTimeout(TIMEOUT_FROM_ENV)`, why have tc-node explicitly handle this variable?

**Comment by mderrien29** [comment]
Hello,

Since this is a common use case (eg. #57 ), I feel like using an environment variable to inject a timeout should be the default practice, without requiring a separate fixture in the test code base, imported in every test and applied manually to every container. It's also useful and easy to setup while you are debugging another issue.

As discussed in the original issue, the current solution works, it just feels right (to me at least) to have that as an option in the library.

**Comment by cristianrgreco** [comment]
> Since this is a common use case (eg. https://github.com/testcontainers/testcontainers-node/pull/57 )

This issue was solved simply by setting the startup timeout, the PR you have raised wouldn't solve the fact that there was a need to configure a startup timeout, it just changes how to do it.

I have 2 reasons why I am not for merging this:
1. It deviates more from testcontainers-java, they have 1000s of users and this isn't a problem they have (which is also why I say this isn't a common issue).
2. It adds more scope for breaking changes. There is currently a very simple API, `withStartupTimeout`, and you could provide any such value there, including from the environment.

For these reasons I won't merge this. If there is a demand or reasons for it which the existing `withStartupTimeout` does not address, then I'm happy to revisit. Will close these for now. Thanks again!
