### ISSUE TITLE
Question: Should a reusable generic container spin up reaper/ryuk?

### ISSUE THREAD

**Issue by henrinormak** [testcontainers/testcontainers-node#452]
Currently, reusable containers are not cleaned up by ryuk, as per [this logic](https://github.com/testcontainers/testcontainers-node/blob/master/src/docker/functions/create-labels.ts#L17-L19), therefore, would it make sense that reusable containers also not  spin up a reaper?

Currently they do this [here](https://github.com/testcontainers/testcontainers-node/blob/master/src/generic-container/generic-container.ts#L89-L91), as that does not check the reusable flag in any way.

This means that if we have several parallel test workers, which all use a singular reusable container, they all still spin up a separate ryuk instance (one per node execution, which in case of jest is one per test suite). This is probably not intended?

**Comment by cristianrgreco** [comment]
Hi @henrinormak, you're right, it's pointless to spin up ryuk in the case of a reusable container. I will raise a PR shortly.

**Comment by cristianrgreco** [comment]
I think will be a little more complicated than I first thought. 

We _could_ simply not start the reaper when starting the container when reuse it set, but for example when building from a Dockerfile, we always start the reaper (to clean up the image), and do not provide a way to set reuse at this point. 

I've taken a look at how this is done in tc-java and indeed `reuse` is defined as an environment variable, instead of an option when building the container. I think that this same approach should be taken here and thus needs a breaking change

**Comment by henrinormak** [comment]
Makes sense, for now, I've manually set ryuk disabled via env in cases where I know that a reusable container is going to be used - it does involve some manual cleanup some times, but it's a decent workaround for not getting many overwhelmed with reaper containers.

One other alternative thought - currently session ID is always generated randomly - testcontainers could also allow injection of this, and then instead of always booting up a reaper (i.e it is only checked whether the singleton exists), it could also check whether an appropriately named container already exists.

This way child processes of a process that started testcontainers could potentially reuse the same session/reaper. With setups like jest and workers, this could be quite beneficial - although it would require a bit of manual setup code to establish this "shared session".

Anyway, this is slightly beyond the scope of this original issue, but thought I'd mention it here.

**Comment by cristianrgreco** [comment]
> Makes sense, for now, I've manually set ryuk disabled via env in cases where I know that a reusable container is going to be used - it does involve some manual cleanup some times, but it's a decent workaround for not getting overwhelmed with reaper containers.

Turns out this issue also exists in tc-java. 

Therefore instead of a breaking change, I will make the simple change as originally suggested, as that will provide a benefit. I will re-visit the original issue after some discussion with some of the other authors.

> One other alternative thought - currently session ID is always generated randomly - testcontainers could also allow injection of this, and then instead of always booting up a reaper (i.e it is only checked whether the singleton exists), it could also check whether an appropriately named container already exists.

> This way child processes of a process that started testcontainers could potentially reuse the same session/reaper. With setups like jest and workers, this could be quite beneficial - although it would require a bit of manual setup code to establish this "shared session", be it via env or whatever. It would also require exposing reaper from testcontainers so that any global setup code could establish this session ahead of starting off child processes that rely on it.

This sounds good. A concern I have is that each instance of tc-node, when provided with a reaper session ID, would need to check for the existence of such a container. I assume we'd need some locking in place, at which point we could be a bottleneck for the concurrent executions, depending on how long it takes to list containers? It may be good to create a discussion out of this.
