### ISSUE TITLE
can it start existing container?

### ISSUE THREAD

**Issue by jayarjo** [testcontainers/testcontainers-node#64]
What if container already exists, with a specific name and everything - will this start it or attempt something else?

**Comment by cristianrgreco** [comment]
It will start a new container each time

**Comment by jayarjo** [comment]
Just encountered the error below:

```
Conflict. The container name ...  is already in use by container ... You have to remove (or rename) that container to be able to reuse that name. 
```

But won't be it a nice feature if you could re-use the container or there are no benefits?

**Comment by cristianrgreco** [comment]
I'm not sure. I can't think of many cases where you'd need to connect to an already running container. Likely the container would have been created by testcontainers in the first place thus you wouldn't create it again

**Comment by cristianrgreco** [comment]
I've spoken to the maintainers of testcontainers-java and they've advised against this functionality as it could result in a few complications. In hindsight I think we should not have added the option to name the container

**Comment by Zomono** [comment]
The maintainers of testcontainers-java have implemented this functionallity by a reuse flag that could be set on their GenericContainer. This flag indicates that a similar container also created by testcontainers with the reuse flag can be reused by another test.

The use case is to speed up test runs and reduce resource usage. If you have a lot of test suits, each spawning e.g. a database container, this could be quite expensive in cpu time and in memory. Each test has to create such a container and wait for it to be ready. Having a bunch of database container at the same time can also hit your memory limit very fast.

Spawning the container globally in the setup and teardown phase of your test library may not be a solution, because then every test suit will spawn the defined containers, even if it is executed as a single test and does not use any container. I tried this setup but it slows down single test runs to much leading in a poor developer expierience.

So please reopen this issue and implement the "reuse"-feature from the java version. (alternatively I could create a new issue?)

**Comment by cristianrgreco** [comment]
@Zomono please raise a new issue
